### PR TITLE
Add `AZURE_LOCATION` as default `--location` in `capi create`

### LINKED ISSUE #120: `AZURE_LOCATION` should be used as the default for `--location`
`az capi` tries to be parallel to or compatible with the Quick Start and CAPI/CAPZ docs, so we shouldn't require the `--location` argument if the user already has `AZURE_LOCATION` set in their environment.

### PR DESCRIPTION
**Pull request by tal66**
Hi, this closes #120.

When --location isn't specified, it's now determined by:
1. config file [defaults]
2. resource-group
3. AZURE_LOCATION
4. still None -> raise RequiredArgumentMissingError

Did I miss anything?

Edit: actually when i think about it, maybe it makes more sense to have config file [defaults] and AZURE_LOCATION both either before resource-group or both after..

### CODE REVIEW

**Comment by tal66** [comment]
changed the order to:
1. config file [defaults]
2. AZURE_LOCATION
3. checked against resource-group (if exists)
4. raise Error

for existing rg, maybe it would make more sense to just take the rg loaction. but i used the above order because: 

a. before my pr, the config file is used first
b. since this project is an extension, i'm not sure how to check if the location came from the config file or from the cli

**Comment by DannyBrito** [comment]
Hello @tal66

The order that you presented is correct to set value for `location` for `az capi create` method priority:

1.  value passed with `--location` flag
2. value specified on config file defaults by `az config set defaults.location=<location>`
3. Environment variable `AZURE_LOCATION`
4. Use location if resource group provided exits 

After looking at bit more I see that there might be a bug on `check_resource_group` method when the resource group is found we should use this location, as you mentioned, by returning it to `az capi create`.  I have opened another issue about this!  #144 

You are definitely in the right track. However, this change should take place on `create_workload_cluster` method for `az capi create` command
It should be similar to setting the defaults of the other arguments. 
And if  `--location` is not passed on the cli the framework will retrieve the `config defaults location` value if exits so you will need to take care of `AZURE_LOCATION` :
https://github.com/Azure/azure-capi-cli-extension/blob/2a24f525b9315d0ae6477812d2ffadb9815f7ae8/src/capi/azext_capi/custom.py#L419

Thank you for your contribution 👍

**Comment by tal66** [comment]
I moved it to `create_workload_cluster`, but didn't set the location like the other parameters with a default - as this way is problematic to test. From what i see, once the module file is read those defaults are set, so by the time i mock an environment variable in the test, the default is already None (it's not checked again every call).

**Review by mboersma — APPROVED** [review]
lgtm! I tested this locally and this seems like the behavior we want. Thanks @tal66!

With this and #141, if you configure a default location or set `AZURE_LOCATION`, you can just do `az capi create` without any arguments.

**Pull request merged**
