### PR TITLE
Updating az capi to be able to deploy KPNG on windows instead of in-tree kube-proxy

### PR DESCRIPTION
**Pull request by marosset**
Signed-off-by: Mark Rossetti <marosset@microsoft.com>

**Description**
Updating az capi to be able to deploy KPNG on windows instead of in-tree kube-proxy

**History Notes**
Updating az capi to be able to deploy KPNG on windows instead of in-tree kube-proxy

---

This checklist is used to make sure that common guidelines for an Azure CLI pull request are followed.

- [ ] The PR title and description has followed the guideline in [Submitting Pull Requests](https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules#submitting-pull-requests).
- [x] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).
- [x] I adhere to the [Error Handling Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/error_handling_guidelines.md).

### CODE REVIEW

**Review by mboersma — COMMENTED** [review]
lgtm, I just want to test it in our pipeline to make sure Windows nodes come up.

**Comment by marosset** [comment]
> lgtm, I just want to test it in our pipeline to make sure Windows nodes come up.

I've been testing it locally but please also test it yourself!

**Comment by marosset** [comment]
Let me edit the history file after https://github.com/Azure/azure-capi-cli-extension/pull/182 merges

**Comment by marosset** [comment]
I updated the HISTORY.rst file

**Review by mboersma — APPROVED** [review]
lgtm!

**Pull request merged**
