### PR TITLE
Add configurable install path for binaries

### LINKED ISSUE #16: Binaries output path should be configurable
In some environments, users won't have access to /usr/local/bin, eg:

```
cecile@Azure:~$ az capi create -n cerobert-test -g test
Command group 'capi' is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
wrote manifest file to cerobert-test.yaml
Do you want to create this Kubernetes cluster "cerobert-test" in the Azure resource group "test"? (y/N): y
Downloading client to "/usr/local/bin/clusterctl" from "https://github.com/kubernetes-sigs/cluster-api/releases/latest/download/clusterctl-linux-amd64"
Connection error while attempting to download client ([Errno 13] Permission denied: '/usr/local/bin/clusterctl')
```

### PR DESCRIPTION
**Pull request by willie-yao**
**Description**
In some environments, users won't have access to /usr/local/bin. This PR adds the `--install-path -ip` flag to `az capi install` so users can specify a specific installation path for binaries.

Fixes #16 

az capi install: Add --install-path flag
---

This checklist is used to make sure that common guidelines for an Azure CLI pull request are followed.

- [ ] The PR title and description has followed the guideline in [Submitting Pull Requests](https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules#submitting-pull-requests).
- [ ] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).
- [ ] I adhere to the [Error Handling Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/error_handling_guidelines.md).

### CODE REVIEW

**Review by mboersma — COMMENTED** [review]
This looks like what we want :+1:. If we can silence the linter I think we're all set.

**Comment by willie-yao** [comment]
@mboersma I'm trying to fix the linter issues right now! I tested the command and had to make a change for it to always install the tools if a path is specified. This is because the current check binary method iterates through every path in the PATH to see if the tools are there already. Would this be the correct design choice or no?

**Comment by mboersma** [comment]
> ...to always install the tools if a path is specified. ... Would this be the correct design choice or no?

I think ideally, we would check the specified path to see if the binary already exists, and skip installing if it does. But the behavior you're describing is probably ok as well.

**Review by mboersma — APPROVED** [review]
/lgtm

**Pull request merged**
