### PR TITLE
make azure management cluster the default

### PR DESCRIPTION
**Pull request by CecileRobertMichon**
**Description**

As part of #46, this makes the default management cluster mode "azure" and renames "kind" to "local". This is to abstract away the implementation of using AKS as the management cluster or kind as the local management cluster, simply giving users the choice between building a management cluster locally on their machine or deploying one in Azure.

**History Notes**

---

This checklist is used to make sure that common guidelines for an Azure CLI pull request are followed.

- [ ] The PR title and description has followed the guideline in [Submitting Pull Requests](https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules#submitting-pull-requests).
- [ ] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).
- [ ] I adhere to the [Error Handling Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/error_handling_guidelines.md).

### CODE REVIEW

**Comment by CecileRobertMichon** [comment]
@mboersma I have no idea how to test this. are there docs on building a dev version of the extension and testing it locally?

**Comment by mboersma** [comment]
> I have no idea how to test this

If you ran the `create-dev-env.sh` script in the root and activated the python virtualenv with `./env/bin/activate`, then you should be set up. Using the `az capi` command will then use your local code, so any changes you make show up immediately.

The Azure CLI has its own tool called `azdev` that's the entry point to linting and testing and other stuff. So `azdev test` should run the few unit tests that we have.

We do mention this briefly near the bottom of README.md, but maybe it should be under docs/ instead.

**Comment by mboersma** [comment]
It looks like this code has rusted with regards to `pylint`: I get the same set of linter errors on the `main` branch now. :-( I'll clean it up in a PR.

**Review by mboersma — APPROVED** [review]
/lgtm

**Pull request merged**
