### PR TITLE
Updating az capi to store name of aks infra rg and the aks vnet as environment variables

### PR DESCRIPTION
**Pull request by bingbing8**
**Description**
Updating az capi to store name of aks infrastructure resource group and the aks vnet as environment variables. They are needed for the scenario that the traffic from internet to k8s API server port 6443 is blocked by a network security group. The solution to that is to run k8s e2e tests in a pod on the aks worker node. This requires that aks cluster and k8s client either in the same vnet or in peered vnets. After aks cluster is created, store the aks infrastructure resource group name and the vnet name so that we can use them when peering the aks vnet and k8s vnet later in the template file.
Also add sshd to devcontainer.json so the binaries can be copied out of the container.

**History Notes**
Updating az capi to store name of aks infrastructure resource group and the aks vnet as environment variables

---

This checklist is used to make sure that common guidelines for an Azure CLI pull request are followed.

- [X] The PR title and description has followed the guideline in [Submitting Pull Requests](https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules#submitting-pull-requests).
- [X] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).
- [X] I adhere to the [Error Handling Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/error_handling_guidelines.md).

### CODE REVIEW

**Review by marosset — APPROVED** [review]
/lgtm 
(I have very little experience with Python :P)

/assign @mboersma

**Review by mboersma — APPROVED** [review]
/lgtm

This is a complicated scenario you're describing, so I'm not sure how to test it. The code looks correct, so 👍🏻.

**Comment by bingbing8** [comment]
> /lgtm
> 
> This is a complicated scenario you're describing, so I'm not sure how to test it. The code looks correct, so 👍🏻.

My next step is to sending PR for the updated test scenario

**Pull request merged**
